### PR TITLE
added option to disable spacer position change 

### PR DESCRIPTION
**Pull request by schmeiserd**
As mentioned in #112 (https://github.com/leafo/sticky-kit/issues/112) by renatorib and solved by corinnekunze (all credits go to her) in Twitter Bootstrap environments the position attribute can cause a buggy behaviour. 
I added an option to disable it if wanted (so I can finally get rid of the awful original Bootstrap Affix, yeah!).

### CODE REVIEW

**Comment by FlxPeters** [comment]
can you merge this? I need this so bad ;-)

**Comment by leafo** [comment]
I recommend disabling the spacer using `spacer: false` option. I don't think this specific option is necessary.

**Comment by schmeiserd** [comment]
Unfortunately setting the spacer-option to false is no solution for the mentioned scenarios (https://github.com/leafo/sticky-kit/issues/112).

**Comment by leecollings-sb** [comment]
@leafo Using `spacer:false` does not fix this issue, please re-open

**Pull request closed without merging**
